ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential curl git libyaml-dev pkg-config unzip \
    libpq-dev libvips && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUN_INSTALL=/usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
ARG BUN_VERSION=1.0.1
RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v${BUN_VERSION}"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json bun.lock* ./
RUN bun install

COPY . .

CMD ["bin/dev"]
